# roles/tomcat/tasks/main.yml
---

- name: install tomcat
  package:
    name: tomcat

- name: Create ROOT directory
  file:
    path: /var/lib/tomcat/webapps/ROOT
    state: directory

- name: Install index.html default page
  file:
    path: /var/lib/tomcat/webapps/ROOT/index.html
    state: touch

- name: start / enable tomcat
  service:
    name: tomcat
    enabled: true
    state: started

- name: include tests
  include_tasks: tests.yml
  tags: tests
